### ISSUE TITLE
Error: No pubspec.yaml file found in the current working directory.

### ISSUE THREAD

**Issue by epomatti** [cirruslabs/docker-images-flutter#27]
I'm getting this error when running the command from the README.md file. I have Ubuntu 18.04.

```
Error: No pubspec.yaml file found in the current working directory.
Run this command from the root of your project. Test files must be called
*_test.dart and must reside in the package's 'test' directory (or one of its
subdirectories).
```
The command I'm running is:

`sudo docker run --rm -it -v ${pwd}:/build cirrusci/flutter:stable flutter test`

My current directory is the root of my project:
```
evandro@mypc:~/Projects/my_app$ ls
android  ios  pubspec.lock  README.md              test
build    lib  pubspec.yaml  my_app.iml
```

**Comment by epomatti** [comment]
Solved it by adding `--workdir /build` in the command for the working directory inside the container.

Final command looks like this:

```
docker run --rm -it -v $PWD:/build --workdir /build cirrusci/flutter:stable flutter test
```

Since I copied this command from the README.md should we fix it there?

**Comment by epomatti** [comment]
Created a pull request with new command

https://github.com/cirruslabs/docker-images-flutter/pull/28

Closing this issue.

**Comment by neilchaudhuri** [comment]
I am just now learning Flutter, and I am confused by a chicken or the egg situation. I would like to use a Docker container like this one for development so I don't have to install anything on my machine to get going, but it seems in order to run the container I need Flutter installed in order to create the directory contents @epomatti reported in his original post. Can anyone help me resolve the paradox?
