### ISSUE TITLE
Fix *-web builds

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/docker-images-flutter#66]
Since the base `cirrusci/android-sdk:29`updated to Ubuntu 20.04 there is an issue with installing Chromium:

https://twitter.com/fedor/status/1268948708902739969

**Comment by Tijs-2** [comment]
Well not sure if it helps but I used the android-sdk:30 docker file and changed a few things so it used the debian:stable base image. With this image I could install the Debian Chromium package (https://packages.debian.org/buster/chromium) and run a web build. It did not fail but not sure if everything is as it should be because i am a bit new into Flutter :)

One important change was that Debian stable does nog have openjdk-8 but had to install it like this:
        && wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add - \
        && add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ \
        && apt-get update \
        && apt-get install -y adoptopenjdk-8-hotspot \

They where very small changes so maybe it could be a solution, so hope it helps.

**Comment by shihaohong** [comment]
Does this mean that new `*-web` builds are not possible for now? 

I'm working on updating the CI for https://github.com/flutter/packages and the web benchmarks are failing and I'm wondering if I should disable them for now in the PR I'm preparing.

**Comment by bartekpacia** [comment]
cc @fkorotkov this issue can be closed, because `*-web` Dockerfiles were removed in #320
